# Generated by Django 5.1.4 on 2024-12-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_field',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_user', max_length=150),
        ),
    ]
