# Generated by Django 5.1.4 on 2024-12-27 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentals', '0002_user_temp_field_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='temp_field',
        ),
    ]
