# Generated by Django 5.1.4 on 2024-12-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentals', '0003_remove_user_temp_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(default='-----', max_length=100),
        ),
    ]
