# Generated by Django 5.1.4 on 2024-12-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentals', '0004_appointment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.CharField(default='--', max_length=100),
        ),
    ]
