# Generated by Django 5.1.4 on 2024-12-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentals', '0006_alter_moodlog_user_alter_notification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
